[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "vershachi"
version = "0.1.0"
description = "Vershachi is a Python-based toolkit designed to streamline the development of machine learning and unlearning applications."
authors = ["mo_shahab <mohdshahabuddinsoharwardi@gmail.com>"]
# Add your long description here
long_description = """
    Your long description goes here.
    You can provide a detailed description of your package, its features, and its intended use.
    Make sure to use proper markdown or reStructuredText syntax.
"""

[tool.poetry.dependencies]
# Add your project dependencies here
python = "^3.10"
numpy = "^1.21.5"
pandas = "^1.3.5"
scikit-learn = "^1.4.1"
torch = "^1.10.1"

[tool.poetry.dev-dependencies]
# Add your development dependencies here
